// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserComputeEngine.proto

// Protobuf Java Version: 3.25.1
package usercompute;

public final class UserComputeEngine {
  private UserComputeEngine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FindFactorsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:usercompute.FindFactorsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 nums = 1;</code>
     * @return A list containing the nums.
     */
    java.util.List<java.lang.Integer> getNumsList();
    /**
     * <code>repeated int32 nums = 1;</code>
     * @return The count of nums.
     */
    int getNumsCount();
    /**
     * <code>repeated int32 nums = 1;</code>
     * @param index The index of the element to return.
     * @return The nums at the given index.
     */
    int getNums(int index);
  }
  /**
   * Protobuf type {@code usercompute.FindFactorsRequest}
   */
  public static final class FindFactorsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:usercompute.FindFactorsRequest)
      FindFactorsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindFactorsRequest.newBuilder() to construct.
    private FindFactorsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindFactorsRequest() {
      nums_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FindFactorsRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              usercompute.UserComputeEngine.FindFactorsRequest.class, usercompute.UserComputeEngine.FindFactorsRequest.Builder.class);
    }

    public static final int NUMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList nums_ =
        emptyIntList();
    /**
     * <code>repeated int32 nums = 1;</code>
     * @return A list containing the nums.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getNumsList() {
      return nums_;
    }
    /**
     * <code>repeated int32 nums = 1;</code>
     * @return The count of nums.
     */
    public int getNumsCount() {
      return nums_.size();
    }
    /**
     * <code>repeated int32 nums = 1;</code>
     * @param index The index of the element to return.
     * @return The nums at the given index.
     */
    public int getNums(int index) {
      return nums_.getInt(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nums_.size(); i++) {
        output.writeInt32(1, nums_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < nums_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(nums_.getInt(i));
        }
        size += dataSize;
        size += 1 * getNumsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof usercompute.UserComputeEngine.FindFactorsRequest)) {
        return super.equals(obj);
      }
      usercompute.UserComputeEngine.FindFactorsRequest other = (usercompute.UserComputeEngine.FindFactorsRequest) obj;

      if (!getNumsList()
          .equals(other.getNumsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNumsCount() > 0) {
        hash = (37 * hash) + NUMS_FIELD_NUMBER;
        hash = (53 * hash) + getNumsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static usercompute.UserComputeEngine.FindFactorsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static usercompute.UserComputeEngine.FindFactorsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static usercompute.UserComputeEngine.FindFactorsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(usercompute.UserComputeEngine.FindFactorsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code usercompute.FindFactorsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:usercompute.FindFactorsRequest)
        usercompute.UserComputeEngine.FindFactorsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                usercompute.UserComputeEngine.FindFactorsRequest.class, usercompute.UserComputeEngine.FindFactorsRequest.Builder.class);
      }

      // Construct using usercompute.UserComputeEngine.FindFactorsRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nums_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsRequest_descriptor;
      }

      @java.lang.Override
      public usercompute.UserComputeEngine.FindFactorsRequest getDefaultInstanceForType() {
        return usercompute.UserComputeEngine.FindFactorsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public usercompute.UserComputeEngine.FindFactorsRequest build() {
        usercompute.UserComputeEngine.FindFactorsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public usercompute.UserComputeEngine.FindFactorsRequest buildPartial() {
        usercompute.UserComputeEngine.FindFactorsRequest result = new usercompute.UserComputeEngine.FindFactorsRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(usercompute.UserComputeEngine.FindFactorsRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          nums_.makeImmutable();
          result.nums_ = nums_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof usercompute.UserComputeEngine.FindFactorsRequest) {
          return mergeFrom((usercompute.UserComputeEngine.FindFactorsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(usercompute.UserComputeEngine.FindFactorsRequest other) {
        if (other == usercompute.UserComputeEngine.FindFactorsRequest.getDefaultInstance()) return this;
        if (!other.nums_.isEmpty()) {
          if (nums_.isEmpty()) {
            nums_ = other.nums_;
            nums_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureNumsIsMutable();
            nums_.addAll(other.nums_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureNumsIsMutable();
                nums_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureNumsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  nums_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList nums_ = emptyIntList();
      private void ensureNumsIsMutable() {
        if (!nums_.isModifiable()) {
          nums_ = makeMutableCopy(nums_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int32 nums = 1;</code>
       * @return A list containing the nums.
       */
      public java.util.List<java.lang.Integer>
          getNumsList() {
        nums_.makeImmutable();
        return nums_;
      }
      /**
       * <code>repeated int32 nums = 1;</code>
       * @return The count of nums.
       */
      public int getNumsCount() {
        return nums_.size();
      }
      /**
       * <code>repeated int32 nums = 1;</code>
       * @param index The index of the element to return.
       * @return The nums at the given index.
       */
      public int getNums(int index) {
        return nums_.getInt(index);
      }
      /**
       * <code>repeated int32 nums = 1;</code>
       * @param index The index to set the value at.
       * @param value The nums to set.
       * @return This builder for chaining.
       */
      public Builder setNums(
          int index, int value) {

        ensureNumsIsMutable();
        nums_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 nums = 1;</code>
       * @param value The nums to add.
       * @return This builder for chaining.
       */
      public Builder addNums(int value) {

        ensureNumsIsMutable();
        nums_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 nums = 1;</code>
       * @param values The nums to add.
       * @return This builder for chaining.
       */
      public Builder addAllNums(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNumsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nums_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 nums = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNums() {
        nums_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:usercompute.FindFactorsRequest)
    }

    // @@protoc_insertion_point(class_scope:usercompute.FindFactorsRequest)
    private static final usercompute.UserComputeEngine.FindFactorsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new usercompute.UserComputeEngine.FindFactorsRequest();
    }

    public static usercompute.UserComputeEngine.FindFactorsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FindFactorsRequest>
        PARSER = new com.google.protobuf.AbstractParser<FindFactorsRequest>() {
      @java.lang.Override
      public FindFactorsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FindFactorsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindFactorsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public usercompute.UserComputeEngine.FindFactorsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FindFactorsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:usercompute.FindFactorsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string factors = 1;</code>
     * @return A list containing the factors.
     */
    java.util.List<java.lang.String>
        getFactorsList();
    /**
     * <code>repeated string factors = 1;</code>
     * @return The count of factors.
     */
    int getFactorsCount();
    /**
     * <code>repeated string factors = 1;</code>
     * @param index The index of the element to return.
     * @return The factors at the given index.
     */
    java.lang.String getFactors(int index);
    /**
     * <code>repeated string factors = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the factors at the given index.
     */
    com.google.protobuf.ByteString
        getFactorsBytes(int index);

    /**
     * <code>optional string error_message = 2;</code>
     * @return Whether the errorMessage field is set.
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string error_message = 2;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string error_message = 2;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code usercompute.FindFactorsResponse}
   */
  public static final class FindFactorsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:usercompute.FindFactorsResponse)
      FindFactorsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindFactorsResponse.newBuilder() to construct.
    private FindFactorsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindFactorsResponse() {
      factors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      errorMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FindFactorsResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              usercompute.UserComputeEngine.FindFactorsResponse.class, usercompute.UserComputeEngine.FindFactorsResponse.Builder.class);
    }

    private int bitField0_;
    public static final int FACTORS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList factors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string factors = 1;</code>
     * @return A list containing the factors.
     */
    public com.google.protobuf.ProtocolStringList
        getFactorsList() {
      return factors_;
    }
    /**
     * <code>repeated string factors = 1;</code>
     * @return The count of factors.
     */
    public int getFactorsCount() {
      return factors_.size();
    }
    /**
     * <code>repeated string factors = 1;</code>
     * @param index The index of the element to return.
     * @return The factors at the given index.
     */
    public java.lang.String getFactors(int index) {
      return factors_.get(index);
    }
    /**
     * <code>repeated string factors = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the factors at the given index.
     */
    public com.google.protobuf.ByteString
        getFactorsBytes(int index) {
      return factors_.getByteString(index);
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errorMessage_ = "";
    /**
     * <code>optional string error_message = 2;</code>
     * @return Whether the errorMessage field is set.
     */
    @java.lang.Override
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string error_message = 2;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_message = 2;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < factors_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, factors_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < factors_.size(); i++) {
          dataSize += computeStringSizeNoTag(factors_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFactorsList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof usercompute.UserComputeEngine.FindFactorsResponse)) {
        return super.equals(obj);
      }
      usercompute.UserComputeEngine.FindFactorsResponse other = (usercompute.UserComputeEngine.FindFactorsResponse) obj;

      if (!getFactorsList()
          .equals(other.getFactorsList())) return false;
      if (hasErrorMessage() != other.hasErrorMessage()) return false;
      if (hasErrorMessage()) {
        if (!getErrorMessage()
            .equals(other.getErrorMessage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFactorsCount() > 0) {
        hash = (37 * hash) + FACTORS_FIELD_NUMBER;
        hash = (53 * hash) + getFactorsList().hashCode();
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static usercompute.UserComputeEngine.FindFactorsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static usercompute.UserComputeEngine.FindFactorsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static usercompute.UserComputeEngine.FindFactorsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(usercompute.UserComputeEngine.FindFactorsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code usercompute.FindFactorsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:usercompute.FindFactorsResponse)
        usercompute.UserComputeEngine.FindFactorsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                usercompute.UserComputeEngine.FindFactorsResponse.class, usercompute.UserComputeEngine.FindFactorsResponse.Builder.class);
      }

      // Construct using usercompute.UserComputeEngine.FindFactorsResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        factors_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        errorMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return usercompute.UserComputeEngine.internal_static_usercompute_FindFactorsResponse_descriptor;
      }

      @java.lang.Override
      public usercompute.UserComputeEngine.FindFactorsResponse getDefaultInstanceForType() {
        return usercompute.UserComputeEngine.FindFactorsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public usercompute.UserComputeEngine.FindFactorsResponse build() {
        usercompute.UserComputeEngine.FindFactorsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public usercompute.UserComputeEngine.FindFactorsResponse buildPartial() {
        usercompute.UserComputeEngine.FindFactorsResponse result = new usercompute.UserComputeEngine.FindFactorsResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(usercompute.UserComputeEngine.FindFactorsResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          factors_.makeImmutable();
          result.factors_ = factors_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.errorMessage_ = errorMessage_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof usercompute.UserComputeEngine.FindFactorsResponse) {
          return mergeFrom((usercompute.UserComputeEngine.FindFactorsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(usercompute.UserComputeEngine.FindFactorsResponse other) {
        if (other == usercompute.UserComputeEngine.FindFactorsResponse.getDefaultInstance()) return this;
        if (!other.factors_.isEmpty()) {
          if (factors_.isEmpty()) {
            factors_ = other.factors_;
            bitField0_ |= 0x00000001;
          } else {
            ensureFactorsIsMutable();
            factors_.addAll(other.factors_);
          }
          onChanged();
        }
        if (other.hasErrorMessage()) {
          errorMessage_ = other.errorMessage_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                ensureFactorsIsMutable();
                factors_.add(bs);
                break;
              } // case 10
              case 18: {
                errorMessage_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList factors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureFactorsIsMutable() {
        if (!factors_.isModifiable()) {
          factors_ = new com.google.protobuf.LazyStringArrayList(factors_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @return A list containing the factors.
       */
      public com.google.protobuf.ProtocolStringList
          getFactorsList() {
        factors_.makeImmutable();
        return factors_;
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @return The count of factors.
       */
      public int getFactorsCount() {
        return factors_.size();
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @param index The index of the element to return.
       * @return The factors at the given index.
       */
      public java.lang.String getFactors(int index) {
        return factors_.get(index);
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the factors at the given index.
       */
      public com.google.protobuf.ByteString
          getFactorsBytes(int index) {
        return factors_.getByteString(index);
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @param index The index to set the value at.
       * @param value The factors to set.
       * @return This builder for chaining.
       */
      public Builder setFactors(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFactorsIsMutable();
        factors_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @param value The factors to add.
       * @return This builder for chaining.
       */
      public Builder addFactors(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFactorsIsMutable();
        factors_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @param values The factors to add.
       * @return This builder for chaining.
       */
      public Builder addAllFactors(
          java.lang.Iterable<java.lang.String> values) {
        ensureFactorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, factors_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFactors() {
        factors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string factors = 1;</code>
       * @param value The bytes of the factors to add.
       * @return This builder for chaining.
       */
      public Builder addFactorsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFactorsIsMutable();
        factors_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string error_message = 2;</code>
       * @return Whether the errorMessage field is set.
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string error_message = 2;</code>
       * @return The errorMessage.
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_message = 2;</code>
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_message = 2;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        errorMessage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        errorMessage_ = getDefaultInstance().getErrorMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_message = 2;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        errorMessage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:usercompute.FindFactorsResponse)
    }

    // @@protoc_insertion_point(class_scope:usercompute.FindFactorsResponse)
    private static final usercompute.UserComputeEngine.FindFactorsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new usercompute.UserComputeEngine.FindFactorsResponse();
    }

    public static usercompute.UserComputeEngine.FindFactorsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FindFactorsResponse>
        PARSER = new com.google.protobuf.AbstractParser<FindFactorsResponse>() {
      @java.lang.Override
      public FindFactorsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FindFactorsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindFactorsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public usercompute.UserComputeEngine.FindFactorsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usercompute_FindFactorsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usercompute_FindFactorsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usercompute_FindFactorsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usercompute_FindFactorsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027UserComputeEngine.proto\022\013usercompute\"\"" +
      "\n\022FindFactorsRequest\022\014\n\004nums\030\001 \003(\005\"=\n\023Fi" +
      "ndFactorsResponse\022\017\n\007factors\030\001 \003(\t\022\025\n\rer" +
      "ror_message\030\002 \001(\t2l\n\030UserComputeEngineSe" +
      "rvice\022P\n\013FindFactors\022\037.usercompute.FindF" +
      "actorsRequest\032 .usercompute.FindFactorsR" +
      "esponse"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_usercompute_FindFactorsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_usercompute_FindFactorsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usercompute_FindFactorsRequest_descriptor,
        new java.lang.String[] { "Nums", });
    internal_static_usercompute_FindFactorsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_usercompute_FindFactorsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usercompute_FindFactorsResponse_descriptor,
        new java.lang.String[] { "Factors", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
