// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataEngineService.proto

// Protobuf Java Version: 3.25.1
package dataengine;

public final class DataEngineService {
  private DataEngineService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dataengine.EngineStatus}
   */
  public enum EngineStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_ERROR = 0;</code>
     */
    NO_ERROR(0),
    /**
     * <code>FILE_NOT_FOUND = 1;</code>
     */
    FILE_NOT_FOUND(1),
    /**
     * <code>FILE_READ_ERROR = 2;</code>
     */
    FILE_READ_ERROR(2),
    /**
     * <code>FILE_WRITE_ERROR = 3;</code>
     */
    FILE_WRITE_ERROR(3),
    /**
     * <code>INVALID_PATH = 4;</code>
     */
    INVALID_PATH(4),
    /**
     * <code>INVALID_INPUT_DELIMITER = 5;</code>
     */
    INVALID_INPUT_DELIMITER(5),
    /**
     * <code>INVALID_INTEGER_FORMAT = 6;</code>
     */
    INVALID_INTEGER_FORMAT(6),
    ;

    /**
     * <code>NO_ERROR = 0;</code>
     */
    public static final int NO_ERROR_VALUE = 0;
    /**
     * <code>FILE_NOT_FOUND = 1;</code>
     */
    public static final int FILE_NOT_FOUND_VALUE = 1;
    /**
     * <code>FILE_READ_ERROR = 2;</code>
     */
    public static final int FILE_READ_ERROR_VALUE = 2;
    /**
     * <code>FILE_WRITE_ERROR = 3;</code>
     */
    public static final int FILE_WRITE_ERROR_VALUE = 3;
    /**
     * <code>INVALID_PATH = 4;</code>
     */
    public static final int INVALID_PATH_VALUE = 4;
    /**
     * <code>INVALID_INPUT_DELIMITER = 5;</code>
     */
    public static final int INVALID_INPUT_DELIMITER_VALUE = 5;
    /**
     * <code>INVALID_INTEGER_FORMAT = 6;</code>
     */
    public static final int INVALID_INTEGER_FORMAT_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EngineStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EngineStatus forNumber(int value) {
      switch (value) {
        case 0: return NO_ERROR;
        case 1: return FILE_NOT_FOUND;
        case 2: return FILE_READ_ERROR;
        case 3: return FILE_WRITE_ERROR;
        case 4: return INVALID_PATH;
        case 5: return INVALID_INPUT_DELIMITER;
        case 6: return INVALID_INTEGER_FORMAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EngineStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EngineStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EngineStatus>() {
            public EngineStatus findValueByNumber(int number) {
              return EngineStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dataengine.DataEngineService.getDescriptor().getEnumTypes().get(0);
    }

    private static final EngineStatus[] VALUES = values();

    public static EngineStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EngineStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dataengine.EngineStatus)
  }

  public interface DataEngineResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dataengine.DataEngineResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 computedResults = 1;</code>
     * @return A list containing the computedResults.
     */
    java.util.List<java.lang.Integer> getComputedResultsList();
    /**
     * <code>repeated int32 computedResults = 1;</code>
     * @return The count of computedResults.
     */
    int getComputedResultsCount();
    /**
     * <code>repeated int32 computedResults = 1;</code>
     * @param index The index of the element to return.
     * @return The computedResults at the given index.
     */
    int getComputedResults(int index);

    /**
     * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
     * @return Whether the engineStatus field is set.
     */
    boolean hasEngineStatus();
    /**
     * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
     * @return The engineStatus.
     */
    dataengine.DataEngineService.EngineStatus getEngineStatus();

    /**
     * <code>required bool success = 3;</code>
     * @return Whether the success field is set.
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 3;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>optional string errorMessage = 4;</code>
     * @return Whether the errorMessage field is set.
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 4;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 4;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code dataengine.DataEngineResponse}
   */
  public static final class DataEngineResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dataengine.DataEngineResponse)
      DataEngineResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataEngineResponse.newBuilder() to construct.
    private DataEngineResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataEngineResponse() {
      computedResults_ = emptyIntList();
      engineStatus_ = 0;
      errorMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataEngineResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dataengine.DataEngineService.internal_static_dataengine_DataEngineResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dataengine.DataEngineService.internal_static_dataengine_DataEngineResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dataengine.DataEngineService.DataEngineResponse.class, dataengine.DataEngineService.DataEngineResponse.Builder.class);
    }

    private int bitField0_;
    public static final int COMPUTEDRESULTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList computedResults_ =
        emptyIntList();
    /**
     * <code>repeated int32 computedResults = 1;</code>
     * @return A list containing the computedResults.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getComputedResultsList() {
      return computedResults_;
    }
    /**
     * <code>repeated int32 computedResults = 1;</code>
     * @return The count of computedResults.
     */
    public int getComputedResultsCount() {
      return computedResults_.size();
    }
    /**
     * <code>repeated int32 computedResults = 1;</code>
     * @param index The index of the element to return.
     * @return The computedResults at the given index.
     */
    public int getComputedResults(int index) {
      return computedResults_.getInt(index);
    }

    public static final int ENGINESTATUS_FIELD_NUMBER = 2;
    private int engineStatus_ = 0;
    /**
     * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
     * @return Whether the engineStatus field is set.
     */
    @java.lang.Override public boolean hasEngineStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
     * @return The engineStatus.
     */
    @java.lang.Override public dataengine.DataEngineService.EngineStatus getEngineStatus() {
      dataengine.DataEngineService.EngineStatus result = dataengine.DataEngineService.EngineStatus.forNumber(engineStatus_);
      return result == null ? dataengine.DataEngineService.EngineStatus.NO_ERROR : result;
    }

    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_ = false;
    /**
     * <code>required bool success = 3;</code>
     * @return Whether the success field is set.
     */
    @java.lang.Override
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bool success = 3;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errorMessage_ = "";
    /**
     * <code>optional string errorMessage = 4;</code>
     * @return Whether the errorMessage field is set.
     */
    @java.lang.Override
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string errorMessage = 4;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 4;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEngineStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < computedResults_.size(); i++) {
        output.writeInt32(1, computedResults_.getInt(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(2, engineStatus_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(3, success_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < computedResults_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(computedResults_.getInt(i));
        }
        size += dataSize;
        size += 1 * getComputedResultsList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, engineStatus_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dataengine.DataEngineService.DataEngineResponse)) {
        return super.equals(obj);
      }
      dataengine.DataEngineService.DataEngineResponse other = (dataengine.DataEngineService.DataEngineResponse) obj;

      if (!getComputedResultsList()
          .equals(other.getComputedResultsList())) return false;
      if (hasEngineStatus() != other.hasEngineStatus()) return false;
      if (hasEngineStatus()) {
        if (engineStatus_ != other.engineStatus_) return false;
      }
      if (hasSuccess() != other.hasSuccess()) return false;
      if (hasSuccess()) {
        if (getSuccess()
            != other.getSuccess()) return false;
      }
      if (hasErrorMessage() != other.hasErrorMessage()) return false;
      if (hasErrorMessage()) {
        if (!getErrorMessage()
            .equals(other.getErrorMessage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getComputedResultsCount() > 0) {
        hash = (37 * hash) + COMPUTEDRESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getComputedResultsList().hashCode();
      }
      if (hasEngineStatus()) {
        hash = (37 * hash) + ENGINESTATUS_FIELD_NUMBER;
        hash = (53 * hash) + engineStatus_;
      }
      if (hasSuccess()) {
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSuccess());
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dataengine.DataEngineService.DataEngineResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dataengine.DataEngineService.DataEngineResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataengine.DataEngineService.DataEngineResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dataengine.DataEngineService.DataEngineResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dataengine.DataEngineResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dataengine.DataEngineResponse)
        dataengine.DataEngineService.DataEngineResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dataengine.DataEngineService.internal_static_dataengine_DataEngineResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dataengine.DataEngineService.internal_static_dataengine_DataEngineResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dataengine.DataEngineService.DataEngineResponse.class, dataengine.DataEngineService.DataEngineResponse.Builder.class);
      }

      // Construct using dataengine.DataEngineService.DataEngineResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        computedResults_ = emptyIntList();
        engineStatus_ = 0;
        success_ = false;
        errorMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dataengine.DataEngineService.internal_static_dataengine_DataEngineResponse_descriptor;
      }

      @java.lang.Override
      public dataengine.DataEngineService.DataEngineResponse getDefaultInstanceForType() {
        return dataengine.DataEngineService.DataEngineResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dataengine.DataEngineService.DataEngineResponse build() {
        dataengine.DataEngineService.DataEngineResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dataengine.DataEngineService.DataEngineResponse buildPartial() {
        dataengine.DataEngineService.DataEngineResponse result = new dataengine.DataEngineService.DataEngineResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dataengine.DataEngineService.DataEngineResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          computedResults_.makeImmutable();
          result.computedResults_ = computedResults_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.engineStatus_ = engineStatus_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.success_ = success_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.errorMessage_ = errorMessage_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dataengine.DataEngineService.DataEngineResponse) {
          return mergeFrom((dataengine.DataEngineService.DataEngineResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dataengine.DataEngineService.DataEngineResponse other) {
        if (other == dataengine.DataEngineService.DataEngineResponse.getDefaultInstance()) return this;
        if (!other.computedResults_.isEmpty()) {
          if (computedResults_.isEmpty()) {
            computedResults_ = other.computedResults_;
            computedResults_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureComputedResultsIsMutable();
            computedResults_.addAll(other.computedResults_);
          }
          onChanged();
        }
        if (other.hasEngineStatus()) {
          setEngineStatus(other.getEngineStatus());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasErrorMessage()) {
          errorMessage_ = other.errorMessage_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasEngineStatus()) {
          return false;
        }
        if (!hasSuccess()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureComputedResultsIsMutable();
                computedResults_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureComputedResultsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  computedResults_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 16: {
                int tmpRaw = input.readEnum();
                dataengine.DataEngineService.EngineStatus tmpValue =
                    dataengine.DataEngineService.EngineStatus.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  engineStatus_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              case 24: {
                success_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                errorMessage_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList computedResults_ = emptyIntList();
      private void ensureComputedResultsIsMutable() {
        if (!computedResults_.isModifiable()) {
          computedResults_ = makeMutableCopy(computedResults_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int32 computedResults = 1;</code>
       * @return A list containing the computedResults.
       */
      public java.util.List<java.lang.Integer>
          getComputedResultsList() {
        computedResults_.makeImmutable();
        return computedResults_;
      }
      /**
       * <code>repeated int32 computedResults = 1;</code>
       * @return The count of computedResults.
       */
      public int getComputedResultsCount() {
        return computedResults_.size();
      }
      /**
       * <code>repeated int32 computedResults = 1;</code>
       * @param index The index of the element to return.
       * @return The computedResults at the given index.
       */
      public int getComputedResults(int index) {
        return computedResults_.getInt(index);
      }
      /**
       * <code>repeated int32 computedResults = 1;</code>
       * @param index The index to set the value at.
       * @param value The computedResults to set.
       * @return This builder for chaining.
       */
      public Builder setComputedResults(
          int index, int value) {

        ensureComputedResultsIsMutable();
        computedResults_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 computedResults = 1;</code>
       * @param value The computedResults to add.
       * @return This builder for chaining.
       */
      public Builder addComputedResults(int value) {

        ensureComputedResultsIsMutable();
        computedResults_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 computedResults = 1;</code>
       * @param values The computedResults to add.
       * @return This builder for chaining.
       */
      public Builder addAllComputedResults(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureComputedResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, computedResults_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 computedResults = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearComputedResults() {
        computedResults_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int engineStatus_ = 0;
      /**
       * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
       * @return Whether the engineStatus field is set.
       */
      @java.lang.Override public boolean hasEngineStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
       * @return The engineStatus.
       */
      @java.lang.Override
      public dataengine.DataEngineService.EngineStatus getEngineStatus() {
        dataengine.DataEngineService.EngineStatus result = dataengine.DataEngineService.EngineStatus.forNumber(engineStatus_);
        return result == null ? dataengine.DataEngineService.EngineStatus.NO_ERROR : result;
      }
      /**
       * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
       * @param value The engineStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEngineStatus(dataengine.DataEngineService.EngineStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        engineStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .dataengine.EngineStatus engineStatus = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEngineStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        engineStatus_ = 0;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>required bool success = 3;</code>
       * @return Whether the success field is set.
       */
      @java.lang.Override
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bool success = 3;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 3;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000004);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 4;</code>
       * @return Whether the errorMessage field is set.
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       * @return The errorMessage.
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        errorMessage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        errorMessage_ = getDefaultInstance().getErrorMessage();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        errorMessage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dataengine.DataEngineResponse)
    }

    // @@protoc_insertion_point(class_scope:dataengine.DataEngineResponse)
    private static final dataengine.DataEngineService.DataEngineResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dataengine.DataEngineService.DataEngineResponse();
    }

    public static dataengine.DataEngineService.DataEngineResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DataEngineResponse>
        PARSER = new com.google.protobuf.AbstractParser<DataEngineResponse>() {
      @java.lang.Override
      public DataEngineResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataEngineResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataEngineResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dataengine.DataEngineService.DataEngineResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReadDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dataengine.ReadDataRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fileInputPath = 1;</code>
     * @return Whether the fileInputPath field is set.
     */
    boolean hasFileInputPath();
    /**
     * <code>required string fileInputPath = 1;</code>
     * @return The fileInputPath.
     */
    java.lang.String getFileInputPath();
    /**
     * <code>required string fileInputPath = 1;</code>
     * @return The bytes for fileInputPath.
     */
    com.google.protobuf.ByteString
        getFileInputPathBytes();
  }
  /**
   * Protobuf type {@code dataengine.ReadDataRequest}
   */
  public static final class ReadDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dataengine.ReadDataRequest)
      ReadDataRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReadDataRequest.newBuilder() to construct.
    private ReadDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReadDataRequest() {
      fileInputPath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReadDataRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dataengine.DataEngineService.internal_static_dataengine_ReadDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dataengine.DataEngineService.internal_static_dataengine_ReadDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dataengine.DataEngineService.ReadDataRequest.class, dataengine.DataEngineService.ReadDataRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FILEINPUTPATH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileInputPath_ = "";
    /**
     * <code>required string fileInputPath = 1;</code>
     * @return Whether the fileInputPath field is set.
     */
    @java.lang.Override
    public boolean hasFileInputPath() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string fileInputPath = 1;</code>
     * @return The fileInputPath.
     */
    @java.lang.Override
    public java.lang.String getFileInputPath() {
      java.lang.Object ref = fileInputPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileInputPath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileInputPath = 1;</code>
     * @return The bytes for fileInputPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileInputPathBytes() {
      java.lang.Object ref = fileInputPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileInputPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFileInputPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileInputPath_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileInputPath_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dataengine.DataEngineService.ReadDataRequest)) {
        return super.equals(obj);
      }
      dataengine.DataEngineService.ReadDataRequest other = (dataengine.DataEngineService.ReadDataRequest) obj;

      if (hasFileInputPath() != other.hasFileInputPath()) return false;
      if (hasFileInputPath()) {
        if (!getFileInputPath()
            .equals(other.getFileInputPath())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFileInputPath()) {
        hash = (37 * hash) + FILEINPUTPATH_FIELD_NUMBER;
        hash = (53 * hash) + getFileInputPath().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dataengine.DataEngineService.ReadDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dataengine.DataEngineService.ReadDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataengine.DataEngineService.ReadDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dataengine.DataEngineService.ReadDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dataengine.ReadDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dataengine.ReadDataRequest)
        dataengine.DataEngineService.ReadDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dataengine.DataEngineService.internal_static_dataengine_ReadDataRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dataengine.DataEngineService.internal_static_dataengine_ReadDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dataengine.DataEngineService.ReadDataRequest.class, dataengine.DataEngineService.ReadDataRequest.Builder.class);
      }

      // Construct using dataengine.DataEngineService.ReadDataRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileInputPath_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dataengine.DataEngineService.internal_static_dataengine_ReadDataRequest_descriptor;
      }

      @java.lang.Override
      public dataengine.DataEngineService.ReadDataRequest getDefaultInstanceForType() {
        return dataengine.DataEngineService.ReadDataRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dataengine.DataEngineService.ReadDataRequest build() {
        dataengine.DataEngineService.ReadDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dataengine.DataEngineService.ReadDataRequest buildPartial() {
        dataengine.DataEngineService.ReadDataRequest result = new dataengine.DataEngineService.ReadDataRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dataengine.DataEngineService.ReadDataRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileInputPath_ = fileInputPath_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dataengine.DataEngineService.ReadDataRequest) {
          return mergeFrom((dataengine.DataEngineService.ReadDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dataengine.DataEngineService.ReadDataRequest other) {
        if (other == dataengine.DataEngineService.ReadDataRequest.getDefaultInstance()) return this;
        if (other.hasFileInputPath()) {
          fileInputPath_ = other.fileInputPath_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFileInputPath()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fileInputPath_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileInputPath_ = "";
      /**
       * <code>required string fileInputPath = 1;</code>
       * @return Whether the fileInputPath field is set.
       */
      public boolean hasFileInputPath() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string fileInputPath = 1;</code>
       * @return The fileInputPath.
       */
      public java.lang.String getFileInputPath() {
        java.lang.Object ref = fileInputPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileInputPath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileInputPath = 1;</code>
       * @return The bytes for fileInputPath.
       */
      public com.google.protobuf.ByteString
          getFileInputPathBytes() {
        java.lang.Object ref = fileInputPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileInputPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileInputPath = 1;</code>
       * @param value The fileInputPath to set.
       * @return This builder for chaining.
       */
      public Builder setFileInputPath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileInputPath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileInputPath = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileInputPath() {
        fileInputPath_ = getDefaultInstance().getFileInputPath();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string fileInputPath = 1;</code>
       * @param value The bytes for fileInputPath to set.
       * @return This builder for chaining.
       */
      public Builder setFileInputPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        fileInputPath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dataengine.ReadDataRequest)
    }

    // @@protoc_insertion_point(class_scope:dataengine.ReadDataRequest)
    private static final dataengine.DataEngineService.ReadDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dataengine.DataEngineService.ReadDataRequest();
    }

    public static dataengine.DataEngineService.ReadDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReadDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<ReadDataRequest>() {
      @java.lang.Override
      public ReadDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReadDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReadDataRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dataengine.DataEngineService.ReadDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WriteDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dataengine.WriteDataRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fileOutputPath = 1;</code>
     * @return Whether the fileOutputPath field is set.
     */
    boolean hasFileOutputPath();
    /**
     * <code>required string fileOutputPath = 1;</code>
     * @return The fileOutputPath.
     */
    java.lang.String getFileOutputPath();
    /**
     * <code>required string fileOutputPath = 1;</code>
     * @return The bytes for fileOutputPath.
     */
    com.google.protobuf.ByteString
        getFileOutputPathBytes();

    /**
     * <code>repeated string data = 2;</code>
     * @return A list containing the data.
     */
    java.util.List<java.lang.String>
        getDataList();
    /**
     * <code>repeated string data = 2;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated string data = 2;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    java.lang.String getData(int index);
    /**
     * <code>repeated string data = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the data at the given index.
     */
    com.google.protobuf.ByteString
        getDataBytes(int index);
  }
  /**
   * Protobuf type {@code dataengine.WriteDataRequest}
   */
  public static final class WriteDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dataengine.WriteDataRequest)
      WriteDataRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WriteDataRequest.newBuilder() to construct.
    private WriteDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WriteDataRequest() {
      fileOutputPath_ = "";
      data_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WriteDataRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dataengine.DataEngineService.internal_static_dataengine_WriteDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dataengine.DataEngineService.internal_static_dataengine_WriteDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dataengine.DataEngineService.WriteDataRequest.class, dataengine.DataEngineService.WriteDataRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FILEOUTPUTPATH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileOutputPath_ = "";
    /**
     * <code>required string fileOutputPath = 1;</code>
     * @return Whether the fileOutputPath field is set.
     */
    @java.lang.Override
    public boolean hasFileOutputPath() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string fileOutputPath = 1;</code>
     * @return The fileOutputPath.
     */
    @java.lang.Override
    public java.lang.String getFileOutputPath() {
      java.lang.Object ref = fileOutputPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileOutputPath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileOutputPath = 1;</code>
     * @return The bytes for fileOutputPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileOutputPathBytes() {
      java.lang.Object ref = fileOutputPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileOutputPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList data_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string data = 2;</code>
     * @return A list containing the data.
     */
    public com.google.protobuf.ProtocolStringList
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated string data = 2;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated string data = 2;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public java.lang.String getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated string data = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the data at the given index.
     */
    public com.google.protobuf.ByteString
        getDataBytes(int index) {
      return data_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFileOutputPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileOutputPath_);
      }
      for (int i = 0; i < data_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileOutputPath_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += computeStringSizeNoTag(data_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dataengine.DataEngineService.WriteDataRequest)) {
        return super.equals(obj);
      }
      dataengine.DataEngineService.WriteDataRequest other = (dataengine.DataEngineService.WriteDataRequest) obj;

      if (hasFileOutputPath() != other.hasFileOutputPath()) return false;
      if (hasFileOutputPath()) {
        if (!getFileOutputPath()
            .equals(other.getFileOutputPath())) return false;
      }
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFileOutputPath()) {
        hash = (37 * hash) + FILEOUTPUTPATH_FIELD_NUMBER;
        hash = (53 * hash) + getFileOutputPath().hashCode();
      }
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dataengine.DataEngineService.WriteDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dataengine.DataEngineService.WriteDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataengine.DataEngineService.WriteDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dataengine.DataEngineService.WriteDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dataengine.WriteDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dataengine.WriteDataRequest)
        dataengine.DataEngineService.WriteDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dataengine.DataEngineService.internal_static_dataengine_WriteDataRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dataengine.DataEngineService.internal_static_dataengine_WriteDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dataengine.DataEngineService.WriteDataRequest.class, dataengine.DataEngineService.WriteDataRequest.Builder.class);
      }

      // Construct using dataengine.DataEngineService.WriteDataRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileOutputPath_ = "";
        data_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dataengine.DataEngineService.internal_static_dataengine_WriteDataRequest_descriptor;
      }

      @java.lang.Override
      public dataengine.DataEngineService.WriteDataRequest getDefaultInstanceForType() {
        return dataengine.DataEngineService.WriteDataRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dataengine.DataEngineService.WriteDataRequest build() {
        dataengine.DataEngineService.WriteDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dataengine.DataEngineService.WriteDataRequest buildPartial() {
        dataengine.DataEngineService.WriteDataRequest result = new dataengine.DataEngineService.WriteDataRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dataengine.DataEngineService.WriteDataRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileOutputPath_ = fileOutputPath_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          data_.makeImmutable();
          result.data_ = data_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dataengine.DataEngineService.WriteDataRequest) {
          return mergeFrom((dataengine.DataEngineService.WriteDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dataengine.DataEngineService.WriteDataRequest other) {
        if (other == dataengine.DataEngineService.WriteDataRequest.getDefaultInstance()) return this;
        if (other.hasFileOutputPath()) {
          fileOutputPath_ = other.fileOutputPath_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ |= 0x00000002;
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFileOutputPath()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fileOutputPath_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                ensureDataIsMutable();
                data_.add(bs);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileOutputPath_ = "";
      /**
       * <code>required string fileOutputPath = 1;</code>
       * @return Whether the fileOutputPath field is set.
       */
      public boolean hasFileOutputPath() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string fileOutputPath = 1;</code>
       * @return The fileOutputPath.
       */
      public java.lang.String getFileOutputPath() {
        java.lang.Object ref = fileOutputPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileOutputPath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileOutputPath = 1;</code>
       * @return The bytes for fileOutputPath.
       */
      public com.google.protobuf.ByteString
          getFileOutputPathBytes() {
        java.lang.Object ref = fileOutputPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileOutputPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileOutputPath = 1;</code>
       * @param value The fileOutputPath to set.
       * @return This builder for chaining.
       */
      public Builder setFileOutputPath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileOutputPath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileOutputPath = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileOutputPath() {
        fileOutputPath_ = getDefaultInstance().getFileOutputPath();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string fileOutputPath = 1;</code>
       * @param value The bytes for fileOutputPath to set.
       * @return This builder for chaining.
       */
      public Builder setFileOutputPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        fileOutputPath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList data_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureDataIsMutable() {
        if (!data_.isModifiable()) {
          data_ = new com.google.protobuf.LazyStringArrayList(data_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string data = 2;</code>
       * @return A list containing the data.
       */
      public com.google.protobuf.ProtocolStringList
          getDataList() {
        data_.makeImmutable();
        return data_;
      }
      /**
       * <code>repeated string data = 2;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated string data = 2;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public java.lang.String getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated string data = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the data at the given index.
       */
      public com.google.protobuf.ByteString
          getDataBytes(int index) {
        return data_.getByteString(index);
      }
      /**
       * <code>repeated string data = 2;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureDataIsMutable();
        data_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 2;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureDataIsMutable();
        data_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 2;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<java.lang.String> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 2;</code>
       * @param value The bytes of the data to add.
       * @return This builder for chaining.
       */
      public Builder addDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureDataIsMutable();
        data_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dataengine.WriteDataRequest)
    }

    // @@protoc_insertion_point(class_scope:dataengine.WriteDataRequest)
    private static final dataengine.DataEngineService.WriteDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dataengine.DataEngineService.WriteDataRequest();
    }

    public static dataengine.DataEngineService.WriteDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WriteDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<WriteDataRequest>() {
      @java.lang.Override
      public WriteDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WriteDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WriteDataRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dataengine.DataEngineService.WriteDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataengine_DataEngineResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataengine_DataEngineResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataengine_ReadDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataengine_ReadDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataengine_WriteDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataengine_WriteDataRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027DataEngineService.proto\022\ndataengine\"\204\001" +
      "\n\022DataEngineResponse\022\027\n\017computedResults\030" +
      "\001 \003(\005\022.\n\014engineStatus\030\002 \002(\0162\030.dataengine" +
      ".EngineStatus\022\017\n\007success\030\003 \002(\010\022\024\n\014errorM" +
      "essage\030\004 \001(\t\"(\n\017ReadDataRequest\022\025\n\rfileI" +
      "nputPath\030\001 \002(\t\"8\n\020WriteDataRequest\022\026\n\016fi" +
      "leOutputPath\030\001 \002(\t\022\014\n\004data\030\002 \003(\t*\246\001\n\014Eng" +
      "ineStatus\022\014\n\010NO_ERROR\020\000\022\022\n\016FILE_NOT_FOUN" +
      "D\020\001\022\023\n\017FILE_READ_ERROR\020\002\022\024\n\020FILE_WRITE_E" +
      "RROR\020\003\022\020\n\014INVALID_PATH\020\004\022\033\n\027INVALID_INPU" +
      "T_DELIMITER\020\005\022\032\n\026INVALID_INTEGER_FORMAT\020" +
      "\0062\240\001\n\nDataEngine\022G\n\010ReadData\022\033.dataengin" +
      "e.ReadDataRequest\032\036.dataengine.DataEngin" +
      "eResponse\022I\n\tWriteData\022\034.dataengine.Writ" +
      "eDataRequest\032\036.dataengine.DataEngineResp" +
      "onse"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dataengine_DataEngineResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dataengine_DataEngineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataengine_DataEngineResponse_descriptor,
        new java.lang.String[] { "ComputedResults", "EngineStatus", "Success", "ErrorMessage", });
    internal_static_dataengine_ReadDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dataengine_ReadDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataengine_ReadDataRequest_descriptor,
        new java.lang.String[] { "FileInputPath", });
    internal_static_dataengine_WriteDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dataengine_WriteDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataengine_WriteDataRequest_descriptor,
        new java.lang.String[] { "FileOutputPath", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
